# Generated by Django 3.1 on 2020-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famedicuser',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='famedicuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
