# Generated by Django 3.0.3 on 2020-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='famedicuser',
            options={'verbose_name': 'Usuario'},
        ),
        migrations.AddField(
            model_name='famedicuser',
            name='profile_foto',
            field=models.ImageField(blank=True, upload_to='', verbose_name='foto de perfil'),
        ),
    ]
