# Generated by Django 3.0.3 on 2020-09-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0002_auto_20200826_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='famedicuser',
            name='updated',
            field=models.BooleanField(default=False, verbose_name='datos actualizados'),
        ),
    ]
