# Generated by Django 3.1 on 2020-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0002_auto_20200814_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='famedicuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='famedicuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='famedicuser',
            name='staff',
            field=models.BooleanField(default=True),
        ),
    ]
