# Generated by Django 3.0.3 on 2020-09-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0004_auto_20200915_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famedicuser',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='nombre(s)'),
        ),
        migrations.AlterField(
            model_name='famedicuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='apellido(s)'),
        ),
        migrations.AlterField(
            model_name='famedicuser',
            name='recovery_email',
            field=models.EmailField(max_length=60, null=True, verbose_name='correo electrónico de recuperación'),
        ),
    ]
