# Generated by Django 3.1.2 on 2020-10-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0007_auto_20201002_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='famedicuser',
            name='id_type',
            field=models.CharField(choices=[('NIT', 'Número NIT con indicativo al final'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PP', 'Pasaporte')], default='CC', max_length=3, verbose_name='tipo de documento'),
        ),
    ]
