# Generated by Django 3.1.3 on 2020-11-09 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0009_tokenaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
