# Generated by Django 3.1.3 on 2020-11-09 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0010_auto_20201109_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
