# Generated by Django 3.1.3 on 2020-11-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0011_auto_20201109_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenaccess',
            name='token',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
