# Generated by Django 3.1.3 on 2020-11-10 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0012_auto_20201109_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenaccess',
            name='datetime_loken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
