# Generated by Django 3.1.3 on 2020-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0013_tokenaccess_datetime_loken'),
    ]

    operations = [
        migrations.AddField(
            model_name='famedicuser',
            name='token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
