# Generated by Django 3.1.3 on 2020-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0014_famedicuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='famedicuser',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
