# Generated by Django 3.1.3 on 2020-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famedic_users', '0015_famedicuser_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='famedicuser',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='famedicuser',
            name='intentos_acceso',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
