# Generated by Django 3.0.3 on 2020-08-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadicacionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.IntegerField(unique=True, verbose_name='número de factura')),
                ('monto_factura', models.IntegerField(verbose_name='monto de la factura')),
                ('file_factura', models.FileField(upload_to='', verbose_name='factura')),
                ('file_aportes', models.FileField(upload_to='', verbose_name='aportes')),
                ('file_soporte', models.FileField(upload_to='', verbose_name='soportes de factura')),
                ('file_ribs', models.FileField(upload_to='', verbose_name='ribs')),
                ('observaciones', models.TextField(verbose_name='observaciones')),
            ],
        ),
    ]
