# Generated by Django 3.0.3 on 2020-09-21 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa_name', models.CharField(default='glosa', max_length=25, verbose_name='nombre de glosa')),
                ('glosa_status', models.BooleanField(choices=[(True, 'Glosa activa'), (False, 'Glosa inactiva')], default=True, verbose_name='estado de la glosa')),
            ],
            options={
                'verbose_name': 'Glosa',
            },
        ),
        migrations.CreateModel(
            name='Locaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locacion_name', models.CharField(default='TAME', max_length=50, verbose_name='nombre de la locación')),
                ('locacion_status', models.BooleanField(choices=[(True, 'Locación activa'), (True, 'Locación inactiva')], default=True, verbose_name='estado activo de la locación')),
            ],
            options={
                'verbose_name': 'Locacion',
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede_name', models.CharField(default='FAMEDIC - IPS', max_length=50, verbose_name='nombre de la sede')),
                ('address_sede', models.CharField(blank=True, max_length=50, verbose_name='dirección')),
                ('sede_status', models.BooleanField(choices=[(True, 'Sede activa'), (False, 'Sede inactiva')], default=True, verbose_name='estado activo de la sede')),
                ('locacion_sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Locaciones', verbose_name='locación de la sede')),
            ],
            options={
                'verbose_name': 'Sede',
            },
        ),
        migrations.CreateModel(
            name='RadicacionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.IntegerField(verbose_name='número de factura')),
                ('monto_factura', models.IntegerField(verbose_name='monto de la factura')),
                ('file_factura', models.FileField(upload_to='', verbose_name='factura')),
                ('file_aportes', models.FileField(upload_to='', verbose_name='aportes')),
                ('file_soporte', models.FileField(upload_to='', verbose_name='soportes de factura')),
                ('file_ribs', models.FileField(upload_to='', verbose_name='ribs')),
                ('regimen_type', models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiario')], default=('CT', 'Contributivo'), max_length=2, verbose_name='regimen')),
                ('observaciones', models.TextField(verbose_name='observaciones')),
                ('aproved', models.CharField(choices=[('SINAP', 'Sin verificar'), ('RADSI', 'Radicado aprobado'), ('RADNO', 'Radicado no aprobado')], default='SINAP', max_length=5, verbose_name='estado de radicado')),
                ('obs_admin', models.TextField(blank=True, null=True, verbose_name='observaciones del administrador')),
                ('glosa_asign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Glosa', verbose_name='glosa')),
                ('radicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sede_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Sedes', verbose_name='sede correspondiente')),
            ],
            options={
                'verbose_name': 'Radicado',
            },
        ),
    ]
