# Generated by Django 3.0.3 on 2020-08-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa_name', models.CharField(default='glosa', max_length=25, verbose_name='nombre de glosa')),
                ('glosa_status', models.BooleanField(default=True, verbose_name='estado de glosa')),
            ],
            options={
                'verbose_name': 'Glosa',
            },
        ),
        migrations.CreateModel(
            name='RadicacionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.IntegerField(verbose_name='número de factura')),
                ('monto_factura', models.IntegerField(verbose_name='monto de la factura')),
                ('file_factura', models.FileField(upload_to='', verbose_name='factura')),
                ('file_aportes', models.FileField(upload_to='', verbose_name='aportes')),
                ('file_soporte', models.FileField(upload_to='', verbose_name='soportes de factura')),
                ('file_ribs', models.FileField(upload_to='', verbose_name='ribs')),
                ('regimen_type', models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiario')], default=('CT', 'Contributivo'), max_length=2, verbose_name='regimen')),
                ('sede_select', models.CharField(choices=[('FMETA', 'FAMEDIC - IPS'), ('FCESP', 'FAMEDIC - IPS CENTRO ESPECIALISTAS'), ('FBASI', 'FAMEDIC - IPS BÁSICA'), ('FAPYP', 'FAMEDIC - PYP'), ('FVILL', 'FAMELAB - VILLAVICENCIO'), ('FACAC', 'FAMEDIC - IPS ACACIAS'), ('FPLPZ', 'FAMEDIC - IPS PUERTO LÓPEZ'), ('FGRAN', 'FAMEDIC - IPS GRANADA'), ('FPGTN', 'FAMEDIC - IPS PUERTO GAITÁN'), ('FCASN', 'FAMEDIC - IPS CASANARE'), ('FLIBR', 'FAMEDIC - IPS LIBERTADORES'), ('FVMSR', 'FAMELAB - VITAL MEDICAL SERVICE'), ('FARAU', 'FAMEDIC - IPS ARAUCA'), ('FTAME', 'FAMEDIC - TAME'), ('FTUNJ', 'FAMEDIC - IPS TUNJA'), ('FDUIT', 'FAMEDIC - IPS DUITAMA'), ('FSOGA', 'FAMEDIC - IPS SOGAMOSO'), ('FCHIQ', 'FAMEDIC - IPS CHIQUINQUIRÁ')], default=('FMETA', 'FAMEDIC - IPS'), max_length=5, verbose_name='sede correspondiente')),
                ('observaciones', models.TextField(verbose_name='observaciones')),
                ('aproved', models.BooleanField(default=False, verbose_name=' radicado aprovado')),
                ('glosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Glosa')),
                ('radicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radicado',
            },
        ),
    ]
