# Generated by Django 3.0.3 on 2020-09-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locaciones',
            options={'verbose_name': 'Locación'},
        ),
    ]
