# Generated by Django 3.0.3 on 2020-08-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radicacionmodel',
            old_name='sede_select',
            new_name='sede_selection',
        ),
    ]
