# Generated by Django 3.0.3 on 2020-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiario')], default='CT', max_length=2, verbose_name='regimen'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='id_radicado',
            field=models.IntegerField(unique=True, verbose_name='número de radicación'),
        ),
    ]
