# Generated by Django 3.0.3 on 2020-08-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='glosa',
        ),
    ]
