# Generated by Django 3.0.3 on 2020-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0002_remove_radicacionmodel_glosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='aproved',
            field=models.BooleanField(default=False, verbose_name='Radicado aprobado'),
        ),
    ]
