# Generated by Django 3.0.3 on 2020-08-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0002_auto_20200826_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Sedes', verbose_name='sede correspondiente'),
        ),
    ]
