# Generated by Django 3.0.3 on 2020-09-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0002_auto_20200921_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locaciones',
            new_name='Locacion',
        ),
        migrations.AlterModelOptions(
            name='locacion',
            options={'verbose_name': 'Locacion'},
        ),
    ]
