# Generated by Django 3.0.3 on 2020-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0002_radicacionmodel_radicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionmodel',
            name='aproved',
            field=models.BooleanField(default=False, verbose_name=' radicado aprovado'),
        ),
    ]
