# Generated by Django 3.0.3 on 2020-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0002_auto_20200820_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('MPLP', 'Famedic - IPS Puerto López'), ('MACA', 'Famedic - IPS Acacias'), ('MVLL', 'Famelab - Villavicencio'), ('CHIQ', 'Famedic - IPS Chiquinquirá'), ('MGRA', 'Famedic - IPS Granada'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('CAQZ', 'Famedic - IPS Caquezá'), ('MPYP', 'Famedic - PYP'), ('ATAM', 'Famedic - Tame'), ('MBAS', 'Famelab - IPS Básica'), ('CLIB', 'Famedic - IPS Libertadores'), ('ARAU', 'Famedic - IPS Arauca'), ('MESP', 'Famedic - IPS Centro Especialistas'), ('SOGA', 'Famedic - IPS Sogamoso'), ('DUIT', 'Famedic - IPS Duitama'), ('CLAB', 'Famelab - Vital Medical Service'), ('TUNJ', 'Famedic - IPS Tunja'), ('CASN', 'Famedic - IPS Casanare')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('SB', 'Subsidiario'), ('CT', 'Contributivo')], default='CT', max_length=2, verbose_name='régimen'),
        ),
    ]
