# Generated by Django 3.0.3 on 2020-08-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0003_auto_20200826_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionmodel',
            name='glosa_asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Glosa'),
        ),
    ]
