# Generated by Django 3.0.3 on 2020-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0003_auto_20200821_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('MPYP', 'Famedic - PYP'), ('CLIB', 'Famedic - IPS Libertadores'), ('CASN', 'Famedic - IPS Casanare'), ('MVLL', 'Famelab - Villavicencio'), ('MPLP', 'Famedic - IPS Puerto López'), ('DUIT', 'Famedic - IPS Duitama'), ('ARAU', 'Famedic - IPS Arauca'), ('SOGA', 'Famedic - IPS Sogamoso'), ('CLAB', 'Famelab - Vital Medical Service'), ('MACA', 'Famedic - IPS Acacias'), ('MGRA', 'Famedic - IPS Granada'), ('CAQZ', 'Famedic - IPS Caquezá'), ('MESP', 'Famedic - IPS Centro Especialistas'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('ATAM', 'Famedic - Tame'), ('MBAS', 'Famelab - IPS Básica'), ('CHIQ', 'Famedic - IPS Chiquinquirá'), ('TUNJ', 'Famedic - IPS Tunja')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
    ]
