# Generated by Django 3.0.3 on 2020-09-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0003_auto_20200922_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='locacion_sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Locacion', verbose_name='locación de la sede'),
        ),
    ]
