# Generated by Django 3.0.3 on 2020-08-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0004_auto_20200827_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='glosa_asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_radicaciones.Glosa', verbose_name='glosa'),
        ),
    ]
