# Generated by Django 3.0.3 on 2020-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0004_auto_20200821_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiario')], default='CT', max_length=2, verbose_name='régimen'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('CAQZ', 'Famedic - IPS Caquezá'), ('MVLL', 'Famelab - Villavicencio'), ('CLAB', 'Famelab - Vital Medical Service'), ('DUIT', 'Famedic - IPS Duitama'), ('CASN', 'Famedic - IPS Casanare'), ('MESP', 'Famedic - IPS Centro Especialistas'), ('CLIB', 'Famedic - IPS Libertadores'), ('MGRA', 'Famedic - IPS Granada'), ('ARAU', 'Famedic - IPS Arauca'), ('MBAS', 'Famelab - IPS Básica'), ('MACA', 'Famedic - IPS Acacias'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('MPYP', 'Famedic - PYP'), ('ATAM', 'Famedic - Tame'), ('SOGA', 'Famedic - IPS Sogamoso'), ('MPLP', 'Famedic - IPS Puerto López'), ('TUNJ', 'Famedic - IPS Tunja'), ('CHIQ', 'Famedic - IPS Chiquinquirá')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
    ]
