# Generated by Django 3.0.3 on 2020-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0004_radicacionmodel_glosa_asign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='aproved',
            field=models.BooleanField(choices=[(True, 'Radicado aprobado'), (False, 'Radicado no aprobado')], default=False, verbose_name='Radicado aprobado'),
        ),
    ]
