# Generated by Django 3.0.3 on 2020-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0005_auto_20200821_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('SB', 'Subsidiario'), ('CT', 'Contributivo')], default='CT', max_length=2, verbose_name='régimen'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('ARAU', 'Famedic - IPS Arauca'), ('MPLP', 'Famedic - IPS Puerto López'), ('MBAS', 'Famelab - IPS Básica'), ('MVLL', 'Famelab - Villavicencio'), ('CLAB', 'Famelab - Vital Medical Service'), ('MGRA', 'Famedic - IPS Granada'), ('CAQZ', 'Famedic - IPS Caquezá'), ('MESP', 'Famedic - IPS Centro Especialistas'), ('MPYP', 'Famedic - PYP'), ('DUIT', 'Famedic - IPS Duitama'), ('MACA', 'Famedic - IPS Acacias'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('CASN', 'Famedic - IPS Casanare'), ('CLIB', 'Famedic - IPS Libertadores'), ('ATAM', 'Famedic - Tame'), ('CHIQ', 'Famedic - IPS Chiquinquirá'), ('TUNJ', 'Famedic - IPS Tunja'), ('SOGA', 'Famedic - IPS Sogamoso')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
    ]
