# Generated by Django 3.0.3 on 2020-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0005_auto_20200827_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionmodel',
            name='obs_admin',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones durante revisión'),
        ),
    ]
