# Generated by Django 3.0.3 on 2020-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0005_auto_20200922_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacion',
            options={'verbose_name': 'Locacione'},
        ),
        migrations.AlterField(
            model_name='locacion',
            name='locacion_status',
            field=models.BooleanField(choices=[(True, 'Locación activa'), (False, 'Locación inactiva')], default=True, verbose_name='estado activo de la locación'),
        ),
    ]
