# Generated by Django 3.0.3 on 2020-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0006_auto_20200821_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='id_radicado',
            field=models.IntegerField(auto_created=True, default=100000, unique=True, verbose_name='número de radicación'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiario')], default='CT', max_length=2, verbose_name='régimen'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('MESP', 'Famedic - IPS Centro Especialistas'), ('MBAS', 'Famelab - IPS Básica'), ('ARAU', 'Famedic - IPS Arauca'), ('SOGA', 'Famedic - IPS Sogamoso'), ('MPLP', 'Famedic - IPS Puerto López'), ('MVLL', 'Famelab - Villavicencio'), ('DUIT', 'Famedic - IPS Duitama'), ('MACA', 'Famedic - IPS Acacias'), ('CLIB', 'Famedic - IPS Libertadores'), ('CLAB', 'Famelab - Vital Medical Service'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('MPYP', 'Famedic - PYP'), ('CASN', 'Famedic - IPS Casanare'), ('CAQZ', 'Famedic - IPS Caquezá'), ('TUNJ', 'Famedic - IPS Tunja'), ('MGRA', 'Famedic - IPS Granada'), ('CHIQ', 'Famedic - IPS Chiquinquirá'), ('ATAM', 'Famedic - Tame')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
    ]
