# Generated by Django 3.0.3 on 2020-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0006_radicacionmodel_obs_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='obs_admin',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones del administrador'),
        ),
    ]
