# Generated by Django 3.0.3 on 2020-09-22 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0006_auto_20200922_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacion',
            options={'verbose_name': 'Sitio'},
        ),
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='file_ribs',
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='file_ribs1',
            field=models.FileField(blank=True, upload_to='', verbose_name='rip 1'),
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='file_ribs2',
            field=models.FileField(blank=True, upload_to='', verbose_name='rib 2'),
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='file_ribs3',
            field=models.FileField(blank=True, upload_to='', verbose_name='rib 3'),
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='file_ribs4',
            field=models.FileField(blank=True, upload_to='', verbose_name='rib 4'),
        ),
    ]
