# Generated by Django 3.0.3 on 2020-08-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0006_auto_20200826_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede_name', models.CharField(default='FAMEDIC - IPS', max_length=25, verbose_name='nombre de la sede')),
                ('locacion_sede', models.CharField(blank=True, max_length=25, verbose_name='localización de la sede')),
                ('glosa_status', models.BooleanField(choices=[(True, 'Sede activa'), (False, 'Sede inactiva')], default=True, verbose_name='estado de la sede')),
            ],
            options={
                'verbose_name': 'Sede',
            },
        ),
        migrations.AlterField(
            model_name='glosa',
            name='glosa_status',
            field=models.BooleanField(choices=[(True, 'Glosa activa'), (False, 'Glosa inactiva')], default=True, verbose_name='estado de la glosa'),
        ),
    ]
