# Generated by Django 3.1 on 2020-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0007_auto_20200922_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionmodel',
            name='datetime_factura',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de la factura'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de radicación'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='file_ribs2',
            field=models.FileField(blank=True, upload_to='', verbose_name='rip 2'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='file_ribs3',
            field=models.FileField(blank=True, upload_to='', verbose_name='rip 3'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='file_ribs4',
            field=models.FileField(blank=True, upload_to='', verbose_name='rip 4'),
        ),
    ]
