# Generated by Django 3.0.3 on 2020-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0007_auto_20200821_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='id_radicado',
            field=models.IntegerField(unique=True, verbose_name='número de radicación'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('SB', 'Subsidiario'), ('CT', 'Contributivo')], default='CT', max_length=2, verbose_name='régimen'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('CASN', 'Famedic - IPS Casanare'), ('ATAM', 'Famedic - Tame'), ('MBAS', 'Famelab - IPS Básica'), ('CHIQ', 'Famedic - IPS Chiquinquirá'), ('MPLP', 'Famedic - IPS Puerto López'), ('CAQZ', 'Famedic - IPS Caquezá'), ('MVLL', 'Famelab - Villavicencio'), ('MESP', 'Famedic - IPS Centro Especialistas'), ('DUIT', 'Famedic - IPS Duitama'), ('TUNJ', 'Famedic - IPS Tunja'), ('ARAU', 'Famedic - IPS Arauca'), ('MGRA', 'Famedic - IPS Granada'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('SOGA', 'Famedic - IPS Sogamoso'), ('CLAB', 'Famelab - Vital Medical Service'), ('CLIB', 'Famedic - IPS Libertadores'), ('MACA', 'Famedic - IPS Acacias'), ('MPYP', 'Famedic - PYP')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
    ]
