# Generated by Django 3.0.3 on 2020-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0007_auto_20200826_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedes',
            name='address_sede',
            field=models.CharField(blank=True, max_length=25, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='locacion_sede',
            field=models.CharField(blank=True, max_length=25, verbose_name='ubicación'),
        ),
    ]
