# Generated by Django 3.0.3 on 2020-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0008_auto_20200821_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('TUNJ', 'Famedic - IPS Tunja'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('MACA', 'Famedic - IPS Acacias'), ('SOGA', 'Famedic - IPS Sogamoso'), ('MVLL', 'Famelab - Villavicencio'), ('MPYP', 'Famedic - PYP'), ('CHIQ', 'Famedic - IPS Chiquinquirá'), ('MPLP', 'Famedic - IPS Puerto López'), ('ARAU', 'Famedic - IPS Arauca'), ('CAQZ', 'Famedic - IPS Caquezá'), ('DUIT', 'Famedic - IPS Duitama'), ('MGRA', 'Famedic - IPS Granada'), ('CLAB', 'Famelab - Vital Medical Service'), ('CASN', 'Famedic - IPS Casanare'), ('MESP', 'Famedic - IPS Centro Especialistas'), ('MBAS', 'Famelab - IPS Básica'), ('ATAM', 'Famedic - Tame'), ('CLIB', 'Famedic - IPS Libertadores')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
    ]
