# Generated by Django 3.1 on 2020-09-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0008_auto_20200928_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radicacionmodel',
            old_name='datetime_factura',
            new_name='datetime_factura1',
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='datetime_factura2',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de la factura'),
        ),
    ]
