# Generated by Django 3.0.3 on 2020-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0008_auto_20200826_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='sede_name',
            field=models.CharField(default='FAMEDIC - IPS', max_length=50, verbose_name='nombre de la sede'),
        ),
    ]
