# Generated by Django 3.0.3 on 2020-08-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0009_auto_20200826_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='address_sede',
            field=models.CharField(blank=True, max_length=50, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='locacion_sede',
            field=models.CharField(blank=True, max_length=50, verbose_name='ubicación'),
        ),
    ]
