# Generated by Django 3.1 on 2020-09-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0009_auto_20200928_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_factura1',
            field=models.DateField(blank=True, null=True, verbose_name='fecha inicial de la factura'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_factura2',
            field=models.DateField(blank=True, null=True, verbose_name='fecha final de la factura'),
        ),
    ]
