# Generated by Django 3.0.3 on 2020-08-21 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_radicaciones', '0010_auto_20200821_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='radicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('DUIT', 'Famedic - IPS Duitama'), ('ARAU', 'Famedic - IPS Arauca'), ('ATAM', 'Famedic - Tame'), ('CHIQ', 'Famedic - IPS Chiquinquirá'), ('MGRA', 'Famedic - IPS Granada'), ('MVLL', 'Famelab - Villavicencio'), ('SOGA', 'Famedic - IPS Sogamoso'), ('MPGA', 'Famedic - IPS Puerto Gaitán'), ('MBAS', 'Famelab - IPS Básica'), ('CASN', 'Famedic - IPS Casanare'), ('MESP', 'Famedic - IPS Centro Especialistas'), ('MPLP', 'Famedic - IPS Puerto López'), ('MPYP', 'Famedic - PYP'), ('MACA', 'Famedic - IPS Acacias'), ('CAQZ', 'Famedic - IPS Caquezá'), ('CLAB', 'Famelab - Vital Medical Service'), ('CLIB', 'Famedic - IPS Libertadores'), ('TUNJ', 'Famedic - IPS Tunja')], default='ARAU', max_length=4, verbose_name='sede correspondiente'),
        ),
    ]
