# Generated by Django 3.0.3 on 2020-10-02 15:53

from django.db import migrations, models
import portal_radicaciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0010_auto_20200928_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='file_ribs1',
        ),
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='file_ribs2',
        ),
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='file_ribs3',
        ),
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='file_ribs4',
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='file_ribs',
            field=models.FileField(blank=True, upload_to='', validators=[portal_radicaciones.models.RadicacionModel.validate_file_extension], verbose_name='rip 1'),
        ),
    ]
