# Generated by Django 3.0.3 on 2020-08-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0010_auto_20200826_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sedes',
            old_name='glosa_status',
            new_name='sede_status',
        ),
    ]
