# Generated by Django 3.0.3 on 2020-08-21 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_radicaciones', '0011_auto_20200821_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='sede_select',
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='id_radicado',
            field=models.IntegerField(default=100000, unique=True, verbose_name='número de radicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='radicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiario')], default='CT', max_length=2, verbose_name='regimen'),
        ),
    ]
