# Generated by Django 3.0.3 on 2020-10-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0011_auto_20201002_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacion',
            name='municipio',
            field=models.CharField(choices=[('ARAU', 'Arauca'), ('BOYC', 'Boyacá'), ('CASN', 'Casanare'), ('CUND', 'Cundinamarca'), ('META', 'Meta')], default='META', max_length=5, verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='locacion',
            name='locacion_name',
            field=models.CharField(default='VILLAVICENCIO', max_length=50, verbose_name='municipio'),
        ),
    ]
