# Generated by Django 3.0.3 on 2020-08-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0012_auto_20200821_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(default='IPS', max_length=4),
            preserve_default=False,
        ),
    ]
