# Generated by Django 3.0.3 on 2020-10-22 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0012_auto_20201002_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 26), verbose_name='fecha de radicación'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiado')], default=('CT', 'Contributivo'), max_length=2, verbose_name='regimen'),
        ),
    ]
