# Generated by Django 3.0.3 on 2020-08-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0013_radicacionmodel_sede_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radicacionmodel',
            name='id_radicado',
        ),
    ]
