# Generated by Django 3.1.2 on 2020-10-29 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0013_auto_20201022_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 29), verbose_name='fecha de radicación'),
        ),
    ]
