# Generated by Django 3.1.3 on 2020-11-09 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0014_auto_20201029_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosa',
            name='glosa_name',
            field=models.CharField(default='glosa', max_length=255, verbose_name='nombre de glosa'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 9), verbose_name='fecha de radicación'),
        ),
    ]
