# Generated by Django 3.0.3 on 2020-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0014_remove_radicacionmodel_id_radicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('FMETA', 'FAMEDIC - IPS'), ('FCESP', 'FAMEDIC - IPS CENTRO ESPECIALISTAS'), ('FBASI', 'FAMEDIC - IPS BÁSICA'), ('FAPYP', 'FAMEDIC - PYP'), ('FVILL', 'FAMELAB - VILLAVICENCIO'), ('FACAC', 'FAMEDIC - IPS ACACIAS'), ('FPLPZ', 'FAMEDIC - IPS PUERTO LÓPEZ'), ('FGRAN', 'FAMEDIC - IPS GRANADA'), ('FPGTN', 'FAMEDIC - IPS PUERTO GAITÁN'), ('FCASN', 'FAMEDIC - IPS CASANARE'), ('FLIBR', 'FAMEDIC - IPS LIBERTADORES'), ('FVMSR', 'FAMELAB - VITAL MEDICAL SERVICE'), ('FARAU', 'FAMEDIC - IPS ARAUCA'), ('FTAME', 'FAMEDIC - TAME'), ('FTUNJ', 'FAMEDIC - IPS TUNJA'), ('FDUIT', 'FAMEDIC - IPS DUITAMA'), ('FSOGA', 'FAMEDIC - IPS SOGAMOSO'), ('FCHIQ', 'FAMEDIC - IPS CHIQUINQUIRÁ')], default=('FACAC', 'FAMEDIC - IPS ACACIAS'), max_length=5, verbose_name='sede correspondiente'),
        ),
    ]
