# Generated by Django 3.0.3 on 2020-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0015_auto_20200824_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='id_factura',
            field=models.IntegerField(verbose_name='número de factura'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='regimen_type',
            field=models.CharField(choices=[('CT', 'Contributivo'), ('SB', 'Subsidiario')], default=('CT', 'Contributivo'), max_length=2, verbose_name='regimen'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='sede_select',
            field=models.CharField(choices=[('FMETA', 'FAMEDIC - IPS'), ('FCESP', 'FAMEDIC - IPS CENTRO ESPECIALISTAS'), ('FBASI', 'FAMEDIC - IPS BÁSICA'), ('FAPYP', 'FAMEDIC - PYP'), ('FVILL', 'FAMELAB - VILLAVICENCIO'), ('FACAC', 'FAMEDIC - IPS ACACIAS'), ('FPLPZ', 'FAMEDIC - IPS PUERTO LÓPEZ'), ('FGRAN', 'FAMEDIC - IPS GRANADA'), ('FPGTN', 'FAMEDIC - IPS PUERTO GAITÁN'), ('FCASN', 'FAMEDIC - IPS CASANARE'), ('FLIBR', 'FAMEDIC - IPS LIBERTADORES'), ('FVMSR', 'FAMELAB - VITAL MEDICAL SERVICE'), ('FARAU', 'FAMEDIC - IPS ARAUCA'), ('FTAME', 'FAMEDIC - TAME'), ('FTUNJ', 'FAMEDIC - IPS TUNJA'), ('FDUIT', 'FAMEDIC - IPS DUITAMA'), ('FSOGA', 'FAMEDIC - IPS SOGAMOSO'), ('FCHIQ', 'FAMEDIC - IPS CHIQUINQUIRÁ')], default=('FMETA', 'FAMEDIC - IPS'), max_length=5, verbose_name='sede correspondiente'),
        ),
    ]
