# Generated by Django 3.1.3 on 2020-11-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0015_auto_20201109_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='id_factura',
            field=models.CharField(max_length=50, verbose_name='número de factura'),
        ),
    ]
