# Generated by Django 3.1.3 on 2020-11-25 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0018_auto_20201111_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 25), verbose_name='fecha de radicación'),
        ),
    ]
