# Generated by Django 3.1.3 on 2020-11-30 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0019_auto_20201125_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 30), verbose_name='fecha de radicación'),
        ),
    ]
