# Generated by Django 3.1.3 on 2020-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0022_glosa_glosa_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glosa',
            name='glosa_valor',
        ),
        migrations.AddField(
            model_name='radicacionmodel',
            name='glosa_valor',
            field=models.IntegerField(null=True, verbose_name='valor asignar a la glosa'),
        ),
    ]
