# Generated by Django 3.1.3 on 2020-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0024_auto_20201201_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='glosa_valor',
            field=models.IntegerField(blank=True, null=True, verbose_name='valor asignar a la glosa'),
        ),
    ]
