# Generated by Django 3.1.3 on 2020-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0026_subglosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subglosa',
            name='subglosa_status',
            field=models.BooleanField(choices=[(True, 'Sublosa activa'), (False, 'Subglosa inactiva')], default=True, verbose_name='estado de la subglosa'),
        ),
    ]
