# Generated by Django 3.1.4 on 2020-12-04 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0028_radicacionmodel_subglosa_asign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 4), verbose_name='fecha de radicación'),
        ),
    ]
