# Generated by Django 3.1.4 on 2020-12-05 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0029_auto_20201204_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 7), verbose_name='fecha de radicación'),
        ),
    ]
