# Generated by Django 3.1.4 on 2020-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0030_auto_20201205_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_factura1',
            field=models.DateField(blank=True, null=True, verbose_name='fecha inicial de la factura'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_factura2',
            field=models.DateField(blank=True, null=True, verbose_name='fecha final de la factura'),
        ),
    ]
