# Generated by Django 3.2.6 on 2021-09-15 14:27

import datetime
from django.db import migrations, models
import portal_radicaciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_radicaciones', '0032_auto_20201209_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacionmodel',
            name='datetime_radicado',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 15), verbose_name='fecha de radicación'),
        ),
        migrations.AlterField(
            model_name='radicacionmodel',
            name='file_ribs',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[portal_radicaciones.models.RadicacionModel.validate_file_extension], verbose_name='rip 1'),
        ),
    ]
